accounts/urls.py
from django.urls import path
from .views import signup_view, login_view, logout_view, delete_view

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('delete/', delete_view, name='delete'),
]

informationPost/urls.py
from django.urls import path

from .views import index, post_create_form_view, board_list_view, board_topic_list_view, post_detail_view, post_update_view, post_delete_view, create_comment_view, delete_comment_view

app_name = 'boards'

urlpatterns=[
    path('', index),
    path('new/', post_create_form_view, name='post-create'),  # 게시물 작성 페이지
    path('<int:id>/delete/', post_delete_view, name='post-delete'),
    path('<str:board_type>/<str:topic>/<int:id>/edit/', post_update_view, name='post-update'),
    path('create_comment/<int:post_id>/', create_comment_view, name='create-comment'),
    path('delete_comment/<int:comment_id>/', delete_comment_view, name='delete-comment'),
    path('<str:board_type>/<str:topic>/<int:id>/', post_detail_view, name='board-topic-detail'),
    path('<str:board_type>/<str:topic>/', board_topic_list_view, name='board-topic-list'),
    path('<str:board_type>/', board_list_view, name='board-list'),
]

lisamate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from lisamate.views import ProfileView, update_profile_view, index2
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='checklist:index', permanent=False)),
    path('checklist/', include('checklist.urls', namespace='checklist')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('profile/', index2),
    path('profile/<int:id>', ProfileView.as_view(), name='profile'),
    path('boards/', include('informationPost.urls', namespace='informationPost')),
    path('profile/edit/<int:id>/', update_profile_view, name='edit-user'),
]

# MEDIA_URL로 들어오면 MEDIA_ROOT에서 정의한 걸 찾아서 사용
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'lisamate.views.warning_view'

templates/mixin/posts/post_line.html
<div class="writepostBox" onclick="location.href='{% url 'boards:board-topic-detail' board_type=post.board_type topic=post.topic id=post.id %}'" >
    <div class="Topicbox">
        <p>[{{post.topic}}]</p>
    </div>
    <div class="postxtbox">
        <p id="postxtText">{{post.title}}</p>
        <p id="writeCount">[{{ post.comment_count }}]</p>
    </div>
    <div class="Writerbox">
        <p id="writerText">{{post.writer}}</p>
    </div>
    <div class="CreateDaybox">
        <p id="CreateDayText">{{post.created_at}}</p>
    </div>
    <div class="viewbox">
        <p id="viewText">{{post.view_count}}</p>
    </div>
</div>