accounts/urls.py
from django.urls import path
from .views import signup_view, login_view, logout_view, delete_view

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('delete/', delete_view, name='delete'),
]

informationPost/urls.py
from django.urls import path

from .views import index, post_create_form_view, board_list_view, board_topic_list_view, post_detail_view, post_update_view, post_delete_view, create_comment_view, delete_comment_view

app_name = 'boards'

urlpatterns=[
    path('', index),
    path('new/', post_create_form_view, name='post-create'),  # 게시물 작성 페이지
    path('<int:id>/delete/', post_delete_view, name='post-delete'),
    path('<str:board_type>/<str:topic>/<int:id>/edit/', post_update_view, name='post-update'),
    path('create_comment/<int:post_id>/', create_comment_view, name='create-comment'),
    path('delete_comment/<int:comment_id>/', delete_comment_view, name='delete-comment'),
    path('<str:board_type>/<str:topic>/<int:id>/', post_detail_view, name='board-topic-detail'),
    path('<str:board_type>/<str:topic>/', board_topic_list_view, name='board-topic-list'),
    path('<str:board_type>/', board_list_view, name='board-list'),
]

lisamate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from lisamate.views import ProfileView, update_profile_view, index2
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='checklist:index', permanent=False)),
    path('checklist/', include('checklist.urls', namespace='checklist')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('profile/', index2),
    path('profile/<int:id>', ProfileView.as_view(), name='profile'),
    path('boards/', include('informationPost.urls', namespace='informationPost')),
    path('profile/edit/<int:id>/', update_profile_view, name='edit-user'),
]

# MEDIA_URL로 들어오면 MEDIA_ROOT에서 정의한 걸 찾아서 사용
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'lisamate.views.warning_view'

checklist/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Schedule(models.Model):
    content = models.TextField(verbose_name='작성 내용')
    date = models.DateField(verbose_name='날짜', null=True) # date(2023,6,15)
    duration = models.CharField(
        verbose_name='기간',
        choices=(
            ('before', '이사 전'),
            ('doing', '이사 중'),
            ('done', '이사 후'),
        ),
        max_length=10
    )
    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name='schedules', null=True, blank=True)
    is_checked = models.BooleanField(verbose_name='체크 여부', default=False)

    def __str__(self):
        return self.content

users/models.py
from django.contrib.auth.models import AbstractUser, UserManager as DjangoUserManager
from django.db import models

class UserManager(DjangoUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('이메일은 필수 값입니다.')
        if not password:
            raise ValueError('비밀번호는 필수 값입니다.')

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('username', email)  # username 값을 email로 설정
        return self.create_user(email, password, **extra_fields)

class User(AbstractUser):
    email = models.EmailField(unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nickname']
    nickname = models.CharField(verbose_name='닉네임', max_length=255, default='아기사자 33')
    image = models.ImageField(verbose_name='이미지', upload_to='image/', null=True, blank=True)
    introduction = models.TextField(verbose_name='소개글', default="이사 준비 중입니다!")
    objects = UserManager()

    def __str__(self):
        return self.email

templates/boards/board_form.html
{% extends 'base2.html' %}
{% load static %}

{% block content %}
<script src="{% static 'javascript/write.js' %}"></script>

<div class="writebar1">
    <p id="writeTitle1">글쓰기</p>
    <p id="subTitle1">정보 게시판 & 후기 게시판 & 우리동네 게시판</p>
    <i class="fa-solid fa-repeat fa-lg"></i>
</div>
<form action = "" method="POST" enctype="multipart/form-data">
    {% csrf_token %} 
    <div class="writebox1">
        <div class="selectBox2">
            <select name="board_type" id="postType1">
                <option value="none" hidden>게시판 선택</option>
                <optgroup label="정보게시판">
                    <option value="0" {% if post.board_type == "information" and post.topic == "월세" %}selected{% endif %}>월세 정보 공유</option>
                    <option value="1" {% if post.board_type == "information" and post.topic == "전세" %}selected{% endif %}>전세 정보 공유</option>
                    <option value="2" {% if post.board_type == "information" and post.topic == "매매" %}selected{% endif %}>매매 정보 공유</option>                    
                </optgroup>
                <optgroup label="후기게시판">
                    <option value="3" {% if post.board_type == "review" and post.topic == "월세" %}selected{% endif %}>월세 후기</option>
                    <option value="4" {% if post.board_type == "review" and post.topic == "전세" %}selected{% endif %}>전세 후기</option>
                    <option value="5" {% if post.board_type == "review" and post.topic == "매매" %}selected{% endif %}>매매 후기</option>
                </optgroup>
                <optgroup label="우리동네 게시판">
                    <option value="6" {% if post.board_type == "hometown" and post.topic == "우리동네" %}selected{% endif %}>우리동네 현황</option>
                    <option value-="7" {% if post.board_type == "hometown" and post.topic == "범죄자" %}selected{% endif %}>범죄자 거주 정보</option>
                </optgroup>
            </select>
            <select name="city" id="location1" onchange="addressKindChange1(this)">
                <option value="none" hidden>시/도 선택</option>
                <option value="Seoul" {% if post.city == "Seoul" %}selected{% endif %}>서울</option>
                <option value="Gyeonggi" {% if post.city == "Gyeonggi" %}selected{% endif %}>경기</option>
                <option value="Incheon" {% if post.city == "Incheon" %}selected{% endif %}>인천</option>
                <option value="Gangwon" {% if post.city == "Gangwon" %}selected{% endif %}>강원</option>
                <option value="Daejeon" {% if post.city == "Daejeon" %}selected{% endif %}>대전</option>
                <option value="Sejong" {% if post.city == "Sejong" %}selected{% endif %}>세종</option>
                <option value="Chungnam" {% if post.city == "Chungnam" %}selected{% endif %}>충남</option>
                <option value="Chungbuk" {% if post.city == "Chungbuk" %}selected{% endif %}>충북</option>
                <option value="Busan" {% if post.city == "Busan" %}selected{% endif %}>부산</option>
                <option value="Ulsan" {% if post.city == "Ulsan" %}selected{% endif %}>울산</option>
                <option value="Gyeongnam" {% if post.city == "Gyeongnam" %}selected{% endif %}>경남</option>
                <option value="Gyeongbuk" {% if post.city == "Gyeongbuk" %}selected{% endif %}>경북</option>
                <option value="Daegu" {% if post.city == "Daegu" %}selected{% endif %}>대구</option>
                <option value="Gwangju" {% if post.city == "Gwangju" %}selected{% endif %}>광주</option>
                <option value="Jeonnam" {% if post.city == "Jeonnam" %}selected{% endif %}>전남</option>
                <option value="Jeonbuk" {% if post.city == "Jeonbuk" %}selected{% endif %}>전북</option>
                <option value="Jeju" {% if post.city == "Jeju" %}selected{% endif %}>제주</option>
            </select>
            <select name="country" id="Location21">
                <option value="none" hidden>구/군 선택</option>
            </select>
        </div>
        <input type="text" id="TitleInput1" name="title" placeholder="제목을 입력해주세요." value="{{ post.title }}">
        <img id="previewImage1" src="#" alt="">
        <div class="toolbox1">
            <label for="imageFile1">
                <i class="fa-regular fa-image"></i>
            </label>
            <input type="file" name="image" accept="image/*" id="imageFile1" style="display: none;">
            <label for="videoFile1">
                <i class="fa-solid fa-video" id="videoIcon1"></i>
            </label>
            <input type="file" name="video" accept="video/*" id="videoFile1" style="display:none;">
            <label for="fileFile1">
                <i class="fa-regular fa-folder" id="folder1"></i>
            </label>
            <input type="file" name="file" accept="file/*" id="fileFile1" style="display: none;">   
            <!-- 파일 선택 시 선택한 파일 이름을 표시할 영역 -->
            <span id="selectedFileName1">{{ post.file.name }}</span>
            <!--나중에 구현
            <i class="fa-solid fa-link"></i>
            <i class="fa-solid fa-location-dot"></i>
            -->
        </div>
        <textarea name="content" id="content1" placeholder="내용을 입력해주세요.">{{ post.content }}</textarea>
    </div>
    <input type="submit" value="등록하기" id="submitButton1">
</form>
<script>
    // 이미지 선택하면 보여주기 
    var imageFileInput = document.getElementById('imageFile1');
    var previewImage = document.getElementById('previewImage1');

    imageFileInput.addEventListener('change', function() {
    var file = imageFileInput.files[0];
    var reader = new FileReader();

    reader.onload = function(e) {
        previewImage.src = e.target.result;
        previewImage.style.width = '30%'; // 이미지의 크기를 50%로 조절
        previewImage.style.height = 'auto'; // 이미지의 높이를 자동으로 조정
    };

    reader.readAsDataURL(file);
    });

    // 파일 선택 시 선택한 파일 이름 표시
    document.getElementById('fileFile1').addEventListener('change', function() {
        const fileInput = this;
        const fileNameElement = document.getElementById('selectedFileName1');
        
        if (fileInput.files.length > 0) {
        fileNameElement.textContent = fileInput.files[0].name;
        } else {
        fileNameElement.textContent = '';
        }
    });
    

</script>
{% endblock %}

templates/boards/board_form2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>boards</title>

</head>
<body>
    <h1>{{ title }}</h1>

    {% comment %} <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <label for="id_image">이미지</label>
            {% if post.image %}
                <p>현재 : <a href="{{ post.image.url }}">{{ post.image.name }}</a></p>
                <p>변경 : <input type="file" name="image" accept="image/*" id="id_image"></p>
            {% else %}
                <input type="file" name="image" accept="image/*" ida="id_image">
            {% endif %}
        </div>
        <div>
            <label for="id_content">내용</label>
            <textarea name="content" id="id_content" cols="30" rows="10">{% if post %}{{ post.content }}{% endif %}
            </textarea>
        </div>
        <div>
            <input type="submit">
        </div>
    </form> {% endcomment %}


    <div class="post_form">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    <div>

        <script>
            document.addEventListener("DOMContentLoaded", function() {
                var boardTypeField = document.getElementById("id_board_type");
                var topicField = document.getElementById("id_topic");
    
                if (boardTypeField && topicField) {
                    boardTypeField.onchange = function() {
                        updateTopicChoices();
                    };
    
                    // 페이지 로드 시 초기 선택지 업데이트
                    updateTopicChoices();
                }
            });
    
            // board_type 필드의 변경 이벤트를 감지하여 topic 필드의 선택지를 업데이트하는 함수
            function updateTopicChoices() {
                var boardTypeField = document.getElementById("id_board_type");
                var topicField = document.getElementById("id_topic");
                var boardType = boardTypeField.value;
                var topicChoices = {
                    'information': [
                        ['전세', '전세'],
                        ['월세', '월세'],
                        ['매매', '매매']
                    ],
                    'review': [
                        ['전세', '전세'],
                        ['월세', '월세'],
                        ['매매', '매매']
                    ],
                    'hometown': [
                        ['우리동네', '우리동네'],
                        ['범죄자', '범죄자']
                    ]
                };
    
                // 선택지 초기화
                topicField.innerHTML = '';
    
                // 선택지 업데이트
                if (boardType in topicChoices) {
                    topicChoices[boardType].forEach(function(choice) {
                        var option = document.createElement('option');
                        option.value = choice[0];
                        option.text = choice[1];
                        topicField.add(option);
                    });
                }
            }
        </script>


</body>
</html>

templates/boards/board_list.html
{% extends 'base2.html' %}
{% load static %}

{% block content %}
<script src="{% static 'javascript/information.js' %}"></script>
<div class="rightTop">
    <div class="pContainer" data-board-type="{{ board_type }}">
        <a href="{% url 'informationPost:board-list' board_type='information' %}">
            <p>정보 게시판</p>
        </a>
        <a href="{% url 'informationPost:board-list' board_type='review' %}">
            <p>후기 게시판</p>
        </a>
        <p id="pBar">|</p>
        <a href="{% url 'informationPost:board-list' board_type='hometown' %}">
            <p id="ptown">우리동네 게시판</p>
        </a>
        <div class="pBackground"></div>
        <div class="pBackground2"></div>
    </div>
    <form>
        <div class="SSbox">
            <select name="location" onchange="addressKindChange(this)">
                <option value="none" hidden>시/도 선택</option>
                <option value="Seoul">서울</option>
                <option value="Gyeonggi">경기</option>
                <option value="Incheon">인천</option>
                <option value="Gangwon">강원</option>
                <option value="Daejeon">대전</option>
                <option value="Sejong">세종</option>
                <option value="Chungnam">충남</option>
                <option value="Chungbuk">충북</option>
                <option value="Busan">부산</option>
                <option value="Ulsan">울산</option>
                <option value="Gyeongnam">경남</option>
                <option value="Gyeongbuk">경북</option>
                <option value="Daegu">대구</option>
                <option value="Gwangju">광주</option>
                <option value="Jeonnam">전남</option>
                <option value="Jeonbuk">전북</option>
                <option value="Jeju">제주</option>
            </select>
            <select name="location2" id="Location2">
                <option value="none" hidden>구/군 선택</option>
            </select>
            <input type="search" id="searchBox" name="searchBox" placeholder="검색어를 입력해주세요.">
            <div class="submitContainer">
                <input type="submit" id="searchSubmit" value="검색">
            </div>
        </div>
    </form>
</div>

{% if board_type == 'information' %}
    <p id="postTitle">정보 게시판</p>
    <p id="postSub">전세 정보 공유 & 월세 정보 공유 & 매매 정보 공유</p>
{% elif board_type == 'review' %}
    <p id="postTitle">후기 게시판</p>
    <p id="postSub"> 월세 후기 & 전세 후기 & 매매 후기 </p>
{% elif board_type == 'hometown' %}
    <p id="postTitle">우리동네 게시판</p>
    <p id="postSub"> 우리동네 현황 & 범죄자 거주 정보</p>
{% endif %}

<select name="sort" id="sort">
    <option value="recent">최신순</option>
    <option value="popularity">인기순</option>
</select>
<hr id="postHr">

<div class="postTopbar">
    <p id="Topic">Topic</p>
    <p id="postwt">제목</p>
    <p id="writer">작성자</p>
    <p id="createDay">작성일</p>
    <p id="view">조회</p>
</div>
<hr id="postBottomHr">

<div class="notificationBox">
    <div class="Topicbox">공지</div>
        <div class="postxtbox">
            <p id="postxtText">LISA MATE 리사 메이트 이용안내 - 나의 이사메이트 리사.</p>
            <p id="writeCount">[892]</p>
        </div>
        <div class="Writerbox">
            <p id="writerText">LISA</p>
        </div>
        <div class="CreateDaybox">
            <p id="CreateDayText">2023.05.26</p>
        </div>
        <div class="viewbox">
            <p id="viewText">3333</p>
        </div>
    </div>

    {% for post in post_list %}
        {% include 'mixin/posts/post_line.html' with detail=False %}
    {% endfor %}
    <!--<div class="paging">페이징?</div>-->
    </div>
</div>

<script>
    // JavaScript 코드
    var pContainer = document.querySelector('.pContainer');
    var boardType = pContainer.dataset.boardType;
    console.log(boardType, " 아아아아");

    if (boardType === 'information') {
        var pBackgrounds = document.querySelectorAll('.pBackground, .pBackground2');
        for (var i = 0; i < pBackgrounds.length; i++) {
            pBackgrounds[i].style.backgroundColor = '#5378FF';
        }
    }

    else if (boardType === 'review') {
        var pBackgrounds = document.querySelectorAll('.pBackground, .pBackground2');
        for (var i = 0; i < pBackgrounds.length; i++) {
            pBackgrounds[i].style.backgroundColor = '#5378FF';
            pBackgrounds[i].style.marginLeft='20.5vw';
        }
    }
    
    else if (boardType === 'hometown') {
        var pBackgrounds = document.querySelectorAll('.pBackground, .pBackground2');
        for (var i = 0; i < pBackgrounds.length; i++) {
            pBackgrounds[i].style.backgroundColor = '#5378FF';
            pBackgrounds[i].style.marginLeft = '29.7vw';
        }
    }
</script>
{% endblock %}

templates/boards/board_list2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>boards</title>
</head>
<body>
    <h1>
        {% if board_type == 'information' %}
            정보 게시판
        {% elif board_type == 'review' %}
            후기 게시판
        {% elif board_type == 'hometown' %}
            우리동네 게시판
        {% endif %}
    </h1>

    <a href="{% url 'boards:post-create' %}">글쓰기</a>
    <div class="post-list">
        <table>
            <tr>
                <th>Topic</th>
                <th>제목</th>
                <th>작성자</th>
                <th>작성일</th>
                <th>조회</th>
            </tr>
            {% for post in post_list %}
                {% include 'mixin/posts/post_line.html' with detail=False %}
            {% endfor %}
        </table>
    </div>

</body>
</html>

templates/boards/information_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>boards</title>
</head>
<body>
    <h1> 정보 게시판 </h1>
    <a href="{% url 'boards:post-create' %}">
        글쓰기
    </a>
    <div class="post-list">
        <table>
            <tr>
                <th>Topic</th>
                <th>제목</th>
                <th>작성자</th>
                <th>작성일</th>
                <th>조회</th>
            </tr>
            {% for post in post_list %}
                    {% include 'mixin/posts/post_line.html' with detail=False %}
            {% endfor %}
        </table>

    </div>
</body>
</html>

templates/boards/post_detail.html
{% extends 'base2.html' %}
{% load static %}

{% block content %}
<script src="{% static 'javascript/post.js' %}"></script>
<div class="writebar">
    <p id="writeTitle">
        {% if board_type == 'information' %}
            <h2>정보 게시판</h2>
        {% elif board_type == 'review' %}
            <h2>후기 게시판</h2>
        {% elif board_type == 'hometown' %}
            <h2>우리동네 게시판</h2>
        {% endif %}
    </p>
    <p id="subTitle">정보 게시판 & 후기 게시판 & 우리동네 게시판</p>
    <!--목록 버튼-->
    <a href="{% url 'informationPost:board-list' board_type=post.board_type%}">
        <i class="fa-solid fa-repeat fa-lg"></i>
    </a>
</div>
<div class="detail_whitebox">
    <div class="category">
        <a>전체 게시판 </a>><a> {{ post.board_type }} </a>><a> {{ post.topic }} 후기</a>
    </div>
    <div class="detail_whitebox_title">
        <div class="Pcontainer">
            <p id="Ptitle">{{post.title}}</p>
            {% if post.writer == request.user %}
                <div class="dropdown">
                    <i class="fa-solid fa-ellipsis-vertical dropdown-icon" onclick="toggleDropdown()"></i>
                    <div class="dropdown-options" id="dropdown-options">
                        <a href="{% url 'boards:post-update' board_type=post.board_type topic=post.topic id=post.id %}">
                            <div class="dropdown-option" onclick="editOption()">수정하기</div><hr>
                        </a>
                        <div class="dropdown-option" onclick="deleteOption('{{ post.id }}')">삭제하기</div>
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="detail_user">
            <img class="detail_userImage" style="width:3.5vw; height:3.5vw" {% if post.writer.image %}src="{{post.writer.image.url}}"{% endif %}></img>
            <div class="detail_user2">
                <a class="detail_nickname">{{post.writer}}</a>
                <div class="detail_user3">
                    <a class="detail_date">{{post.created_at}} </a>
                    <p class="detail_line"> | </p>
                    <a class="detail_place">{{post.city}} {{post.country}}</a>
                    <p class="detail_line"> | </p>
                    <a class=" detail_see">조회 </a>
                    <a class="detail_see">{{post.view_count}}</a>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="inputText">
        {% if post.image %}
            <p><img src="{{ post.image.url }}" alt="이미지" style="width:30%; height:auto;"></p>
        {% endif %}
        <p class="detail_text">{{post.content}} </p>
        {% if post.file %}
            <p>파일: <a href="{{ post.file.url }}">{{ post.file}}</a></p>
        {% endif %}
    </div>
</div>

<div class="detail_bottom">
    <button id="like" onclick="toggleLikeIcon()"><i class="fa-solid fa-heart"></i> 좋아요 <i id="icon1" class="fa-solid fa-chevron-down"></i></button>
    <button id="comment" onclick="toggleCommentIcon()"><i class="fa-solid fa-comment"></i> 댓글 <i id="icon2" class="fa-solid fa-chevron-down"></i></button>
    <div id="comment-list" style="display: none;">
        <!-- 댓글 리스트 내용 -->
        <button class="comment_title" onclick="toggleCommentForm()" id="writebtn">댓글쓰기</button>
        <form id="comment-form" style="display: none;">
            <textarea rows="10" cols="120"></textarea>
            <br>
            <button class="comment_correct" type="submit">완료</button>
        </form>
        {% for comment in comments %}
        <div class="comment_box">
            <div class="comment_user">
                <img class="comment_userImage" style="width:2vw; height:2vw" {% if comment.writer.image  %}src="{{comment.writer.image.url}}" {% endif %}></img>
                <a class="comment_nickname">{{ comment.writer }}</a>

                <div class="comment_dropdown1">
                    <i class="fa-solid fa-ellipsis-vertical dropdown-icon" onclick="comment_toggleDropdown()"></i>
                    <div class="comment_dropdown-options" id="comment_dropdown-options">
                        <div class="comment_dropdown-option" onclick="comment_deleteOption({{ comment.id }})">삭제하기</div>
                    </div>
                </div>
            </div>
            <a class="comment_text">{{ comment.content }}</a><br><br>
            <div class="flexContainer">
                <a class="comment_date">{{ comment.created_at }}</a>
                <button id="comment_like"><i class="fa-solid fa-heart"></i><a>1</a></button>
            </div>
        </div>
        {% endfor %}

        <form action="{% url 'boards:create-comment' post_id=post.id %}" method="POST">
            {% csrf_token %}
            <div class="comment_box">
                <div class="comment_user">
                    <img class="comment_userImage" style="width:2vw; height:2vw" {% if user.image %}src="{{user.image.url}}"{% endif %}></img>
                    <a class="comment_nickname">{{user.nickname}}</a>
                    <div class="comment_dropdown">
                        <i class="fa-solid fa-ellipsis-vertical dropdown-icon" onclick="comment_toggleDropdown()"></i>
                        <div class="comment_dropdown-options" id="comment_dropdown-options">
                        
                        {% comment %} <div class="comment_dropdown-option" onclick="comment_deleteOption({{ comment.id }})">삭제하기</div> {% endcomment %}
                    </div>
                </div>
            </div>
            <input type="text" id="comment_text1" name='content'><br>
            <div class="buttonContainer">
                <button id="comment_like1" type="submit">완료</button>
            </div>
        </form>
    </div>
</div>


<script>
    function deleteOption(postId) {
        var result = confirm("정말로 삭제하시겠습니까?");
        if (result) {
            var postId = "{{ post.id }}";
            var url = "{% url 'boards:post-delete' id=0 %}".replace('0', postId);
            window.location.href = url;
        } else {
            // 삭제 취소
        }
    }

    function comment_deleteOption(commentId) {
        var result = confirm("댓글 삭제하시겠습니까?");
        if (result) {
        var url = `/boards/delete_comment/${commentId}/`;
            
            // AJAX 요청 보내기
            var xhr = new XMLHttpRequest();
            xhr.open('POST', url);
            xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');
            xhr.onload = function () {
                if (xhr.status === 200) {
                    // 성공적으로 삭제되었을 경우에 대한 처리
                    window.location.reload();  // 페이지 새로고침
                } else {
                    // 오류 발생 시에 대한 처리
                    console.error(xhr.responseText);
                }
            };
            xhr.send();
        } else {
            // 삭제 취소
        }

    }
    
</script>
{% endblock %}

templates/boards/post_detail2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>boards</title>
</head>
<body>
    <h1>post detail 화면</h1>
    {% if board_type == 'information' %}
        <h2>정보 게시판</h2>
    {% elif board_type == 'review' %}
        <h2>후기 게시판</h2>
    {% elif board_type == 'hometown' %}
        <h2>우리동네 게시판</h2>
    {% endif %}
    <div class="post-detail">
        <p> 전체 게시판 &gt; {{ post.board_type }} &gt; {{ post.topic }} </p>
        <p>제목 : {{post.title}} </p>
        <p>작성자 : {{post.writer}}</p>
        <p>날짜 : {{post.created_at}} | 구역 : {{post.city}} {{post.country}} | 조회수 : {{post.view_count}} </p>
        {% if post.image %}
            <p>이미지: <img src="{{ post.image.url }}" alt="이미지"></p>
        {% endif %}
        <p>내용 :  {{post.content}} </p>
        {% if post.file %}
            <p>파일: <a href="{{ post.file.url }}">{{ post.file}}</a></p>
        {% endif %}
    </div>

    <a href="{% url 'boards:post-update' board_type=post.board_type topic=post.topic id=post.id %}">수정하기</a>
    <a href="#" onclick="confirmDelete(/*{{ post.id }}*/)">삭제하기</a>

    <script>
        function confirmDelete(postId) {
            var result = confirm("정말로 삭제하시겠습니까?");
            if (result) {
                var postId = "{{ post.id }}";
                var url = "{% url 'boards:post-delete' id=0 %}".replace('0', postId);
                window.location.href = url;
            } else {
                // 삭제 취소
            }
        }
        </script>
</body>
</html>