accounts/urls.py
from django.urls import path
from .views import signup_view, login_view, logout_view, delete_view

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('delete/', delete_view, name='delete'),
]

checklist/urls.py
from django.urls import path

from .views import index, create_schedule_view, calendar_view, get_schedule_view, update_schedule_view, delete_schedule_view

app_name = 'checklist'

urlpatterns = [
    path('', index, name='index'),
    path('calendar/', calendar_view, name='calendar'),
    path('create_schedule/', create_schedule_view, name='schedule-create'),
    path('calendar/get_schedule/', get_schedule_view, name='schedule-get'),
    path('edit/<int:id>/', update_schedule_view, name='schedule-update'),
    path('delete/<int:id>/', delete_schedule_view, name='schedule-delete'),

]

informationPost/urls.py
from django.urls import path

from .views import index, post_create_form_view, board_list_view, board_topic_list_view, post_detail_view, post_update_view, post_delete_view, create_comment_view, delete_comment_view

app_name = 'boards'

urlpatterns=[
    path('', index),
    path('new/', post_create_form_view, name='post-create'),  # 게시물 작성 페이지
    path('<int:id>/delete/', post_delete_view, name='post-delete'),
    path('<str:board_type>/<str:topic>/<int:id>/edit/', post_update_view, name='post-update'),
    path('create_comment/<int:post_id>/', create_comment_view, name='create-comment'),
    path('delete_comment/<int:comment_id>/', delete_comment_view, name='delete-comment'),
    path('<str:board_type>/<str:topic>/<int:id>/', post_detail_view, name='board-topic-detail'),
    path('<str:board_type>/<str:topic>/', board_topic_list_view, name='board-topic-list'),
    path('<str:board_type>/', board_list_view, name='board-list'),
]

lisamate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from lisamate.views import ProfileView, update_profile_view, index2
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='checklist:index', permanent=False)),
    path('checklist/', include('checklist.urls', namespace='checklist')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('profile/', index2),
    path('profile/<int:id>', ProfileView.as_view(), name='profile'),
    path('boards/', include('informationPost.urls', namespace='informationPost')),
    path('profile/edit/<int:id>/', update_profile_view, name='edit-user'),
]

# MEDIA_URL로 들어오면 MEDIA_ROOT에서 정의한 걸 찾아서 사용
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'lisamate.views.warning_view'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LisaMate</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" href="{% static 'css/checklist.css' %}">
    <link rel="stylesheet" href="{% static 'css/profile_form.css' %}">
    <script src="{% static 'javascript/checklist.js' %}"></script>
    <script src="https://kit.fontawesome.com/d4b61b3d04.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="Middle">
        <div class="Mcircle"></div>
    </div>
    <div class="top">
        <p>My Check list</p>
        <div class="icon">
            <a href="{% url 'profile' id=user.id %}" ><i class="fa-solid fa-user fa-2xl"></i></a>
            <a href="{% url 'checklist:index' %}" ><i class="fa-solid fa-house fa-2xl"></i></a>
        </div>
    </div>

    <div class="logo">
        <a href="{% url 'checklist:index' %}">
            <p>LISA MATE</p>
        </a>
    </div>

    <div class="all">
        <div class="left">
            <div class="userBox">
                <div class="user">USER</div>
                <div class="userbox">
                    <img class="userImage" {% if user.image %}src="{{user.image.url}}"{% endif %}></img>
                    <div class="name">{{ user.nickname }}</div>
                    <div class="email">{{ user.email}}</div>
                    <div class="explain">{{ user.introduction }}</div>
                    <div class="button-container">
                        <a href="{% url 'boards:post-create' %}">
                            <button type="button" id="pen">
                                <img src="{% static 'image/pen.png' %}">글쓰기
                            </button>
                        </a>
                        <a href="{% url 'profile' id=user.id %}">
                            <button type="button" id="setting">
                                <img src="{% static 'image/setting.png' %}">프로필 편집/설정
                            </button>
                        </a>
                    </div>
                </div>
            </div>

            <div class="menu">
                <div class="checklist">체크리스트</div>
                <div class="checklistcircle"></div>
                <div class="text1">
                    <div class="checklistText">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'checklist:index' %}">
                            <p>체크리스트</p>
                        </a>
                    </div>
                    <div class="calText">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'checklist:calendar' %}">
                            <p>캘린더</p>
                        </a>
                    </div>
                </div>
                <div class="noticeboard">게시판</div>
                <div class="noticeboardcircle"></div>
                <div class="text2">
                    <div class="notice">
                        <a href="{% url 'informationPost:board-list' board_type='information' %}">
                            <p>정보 게시판</p>
                        </a>
                    </div>
                    <div class="monthly">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='information' topic='월세' %}">
                            <p>월세 정보 공유</p>
                        </a>
                    </div>
                    <div class="Jeonse">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='information' topic='전세' %}">
                            <p>전세 정보 공유</p>
                        </a>
                    </div>
                    <div class="bargain">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='information' topic='매매' %}">
                            <p>매매 정보 공유</p>
                        </a>
                    </div>
                    <hr>
                </div>
                <div class="text3">
                    <div class="review">
                        <a href="{% url 'informationPost:board-list' board_type='review' %}">
                            <p>후기 게시판</p>
                        </a>
                    </div>
                    <div class="monthlyReview">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='review' topic='월세' %}">
                            <p>월세 후기</p>
                        </a>
                    </div>
                    <div class="JeonseReview">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='review' topic='전세' %}">
                            <p>전세 후기</p>
                        </a>
                    </div>
                    <div class="bargainReview">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='review' topic='매매' %}">
                            <p>매매 후기</p>
                        </a>
                    </div>
                    <hr>
                </div>
                <div class="text4">
                    <div class="town">
                        <a href="{% url 'informationPost:board-list' board_type='hometown' %}">
                            <p>우리동네 게시판</p>
                        </a>
                    </div>
                    <div class="situation">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='hometown' topic='우리동네' %}">
                            <p>우리동네 현황</p>
                        </a>
                    </div>
                    <div class="criminal">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='hometown' topic='범죄자' %}">
                            <p>범죄자 거주 정보</p>
                        </a>
                    </div>
                </div>
            </div>
            <div class="scheduleTitle">Schedule</div>
            {% block schedules %}
            {% block schedule_data %}
            {% if schedules %}
                <div class="scheduleBox">
                    {% for schedule in schedules %}
                        {% if schedule.date and schedule.date|date:"Y-m-d" == now|date:"Y-m-d" %}
                            <div class="scheduleText">
                                <p>{{ schedule.date|date:"m/d" }}</p>
                                <p>{{ schedule.content }}</p>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            {% else %}
                <div class="scheduleBox">
                    <img src="{% static 'image/sleepy.png' %}">
                    <div class="scheduleText"> 
                        <p>오늘의 일정이 없습니다.</p>
                    </div>
                </div>
            {% endif %}
            {% endblock %}
            {% endblock %}
        

        </div>
        <div class="right">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

templates/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LisaMate</title>
    <link rel="stylesheet" href="{% static 'css/base2.css' %}">
    <link rel="stylesheet" href="{% static 'css/post.css' %}">
    <link rel="stylesheet" href="{% static 'css/write.css' %}">
    <link rel="stylesheet" href="{% static 'css/information.css' %}">
    <script src="{% static 'javascript/post.js' %}"></script>
    <script src="{% static 'javascript/write.js' %}"></script>
    <script src="{% static 'javascript/information.js' %}"></script>
    <script src="https://kit.fontawesome.com/d4b61b3d04.js" crossorigin="anonymous"></script>
</head>

<body>
    <div class="top">
        <p>LISA MATE</p>
        <div class="icon">
            <a href="{% url 'profile' id=user.id%}"><i class="fa-solid fa-user fa-2xl"></i></a>
            <a href="{% url 'checklist:index' %}"><i class="fa-solid fa-house fa-2xl"></i></a>
        </div>
    </div>

    <div class="topBox">
        <div class="topBlueBox"></div>
        <div class="topCircle"></div>
        <p id="p1">LISA</p><br>
        <p id="p2">MATE</p>
        <div class="miniTitle">
            <p id="mini">Move Checklist Service</p>
        </div>
        <div class="topbar"></div>
        <p id="mini2">나의 이사메이트 리사.</p>
    </div>

    <div class="all">
        <div class="left">
            <div class="userBox">
                <div class="user">USER</div>
                <div class="userbox">
                    <img class="userImage" {% if user.image %}src="{{user.image.url}}"{% endif %} alt=""></img>
                    <div class="name">{{ user.nickname }}</div>
                    <div class="email">{{ user.email}}</div>
                    <div class="explain">{{ user.introduction }}</div>
                    <div class="button-container">
                        <a href="{% url 'boards:post-create' %}">
                            <button type="button" id="pen">
                                <img src="{% static 'image/pen.png' %}">글쓰기
                            </button>
                        </a>
                        <a href="{% url 'profile' id=user.id%}">
                            <button type="button" id="setting">
                                <img src="{% static 'image/setting.png' %}">프로필 편집/설정
                            </button>
                        </a>
                    </div>
                </div>
            </div>
    
            <div class="menu">
                <div class="checklist">체크리스트</div>
                <div class="checklistcircle"></div>
                <div class="text1">
                    <div class="checklistText">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'checklist:index' %}">
                            <p>체크리스트</p>
                        </a>
                    </div>
                    <div class="calText">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'checklist:calendar' %}">
                            <p>캘린더</p>
                        </a>
                    </div>
                </div>
                <div class="noticeboard">게시판</div>
                <div class="noticeboardcircle"></div>
                <div class="text2">
                    <div class="notice">
                        <a href="{% url 'informationPost:board-list' board_type='information' %}">
                            <p>정보 게시판</p>
                        </a>
                    </div>
                    <div class="monthly">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='information' topic='월세' %}">
                            <p>월세 정보 공유</p>
                        </a>
                    </div>
                    <div class="Jeonse">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='information' topic='전세' %}">
                            <p>전세 정보 공유</p>
                        </a>
                    </div>
                    <div class="bargain">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='information' topic='매매' %}">
                            <p>매매 정보 공유</p>
                        </a>
                    </div>
                    <hr>
                </div>
                <div class="text3">
                    <div class="review">
                        <a href="{% url 'informationPost:board-list' board_type='review' %}">
                            <p>후기 게시판</p>
                        </a>
                    </div>
                    <div class="monthlyReview">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='review' topic='월세' %}">
                            <p>월세 후기</p>
                        </a>
                    </div>
                    <div class="JeonseReview">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='review' topic='전세' %}">
                            <p>전세 후기</p>
                        </a>
                    </div>
                    <div class="bargainReview">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='review' topic='매매' %}">
                            <p>매매 후기</p>
                        </a>
                    </div>
                    <hr>
                </div>
                <div class="text4">
                    <div class="town">
                        <a href="{% url 'informationPost:board-list' board_type='hometown' %}">
                            <p>우리동네 게시판</p>
                        </a>
                    </div>
                    <div class="situation">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='hometown' topic='우리동네' %}">
                            <p>우리동네 현황</p>
                        </a>
                    </div>
                    <div class="criminal">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='hometown' topic='범죄자' %}">
                            <p>범죄자 거주 정보</p>
                        </a>
                    </div>
                </div>
            </div>
            <div class="scheduleTitle">Schedule</div>
            {% block schedule_data %}
            {% if schedules %}
                <div class="scheduleBox">
                    {% for schedule in schedules %}
                        {% if schedule.date and schedule.date|date:"Y-m-d" == now|date:"Y-m-d" %}
                            <div class="scheduleText">
                                <p>{{ schedule.date|date:"m/d" }}</p>
                                <p>{{ schedule.content }}</p>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            {% else %}
                <div class="scheduleBox">
                    <img src="{% static 'image/sleepy.png' %}">
                    <div class="scheduleText"> 
                        <p>오늘의 일정이 없습니다.</p>
                    </div>
                </div>
            {% endif %}
            {% endblock %} 

        </div>
        <div class="right">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

templates/basic2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LisaMate</title>
    <link rel="stylesheet" href="../static/css/basic.css">
    <script src="https://kit.fontawesome.com/d4b61b3d04.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="Middle">
        <div class="Mcircle"></div>
    </div>
    <div class="top">
        <p>My Check list</p>
        <div class="icon">
            <i class="fa-solid fa-user fa-2xl"></i>
            <i class="fa-solid fa-house fa-2xl"></i>
            <div class="bell">
                <i class="fa-solid fa-bell fa-2xl"></i>
                <div class="redcircle"></div>
            </div>
        </div>
    </div>

    <div class="logo">
        <p>LISA MATE</p>
    </div>

    <div class="all">
        <div class="left">
            <div class="userBox">
                <div class="user">USER</div>
                <div class="userbox">
                    <div class="userImage"></div>
                    <div class="name">아기사자 33</div>
                    <div class="email">LIKEALION@333</div>
                    <div class="explain">이사 준비 중입니다!</div>
                    <div class="button-container">
                        <button type="button" id="pen">
                            <img src="../static/image/pen.PNG">글쓰기
                        </button>
                        <button type="button" id="setting">
                            <img src="../static/image/setting.png">프로필 편집/설정
                        </button>
                    </div>
                </div>
            </div>

            <div class="menu">
                <div class="checklist">체크리스트</div>
                <div class="checklistcircle"></div>
                <div class="text1">
                    <div class="checklistText">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <p>체크리스트</p>
                    </div>
                    <div class="calText">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <p>캘린더</p>
                    </div>
                </div>
                <div class="noticeboard">게시판</div>
                <div class="noticeboardcircle"></div>
                <div class="text2">
                    <div class="notice">
                        <p>정보 게시판</p>
                    </div>
                    <div class="monthly">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <p>월세 정보 공유</p>
                    </div>
                    <div class="Jeonse">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <p>전세 정보 공유</p>
                    </div>
                    <div class="bargain">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <p>매매 정보 공유</p>
                    </div>
                    <hr>
                </div>
                <div class="text3">
                    <div class="review">
                        <p>후기 게시판</p>
                    </div>
                    <div class="monthlyReview">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <p>월세 후기</p>
                    </div>
                    <div class="JeonseReview">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <p>전세 후기</p>
                    </div>
                    <div class="bargainReview">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <p>매매 후기</p>
                    </div>
                    <hr>
                </div>
                <div class="text4">
                    <div class="town">
                        <p>우리동네 게시판</p>
                    </div>
                    <div class="situation">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <p>우리동네 현황</p>
                    </div>
                    <div class="criminal">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <p>범죄자 거주 정보</p>
                    </div>
                </div>
            </div>
            <div class="scheduleTitle">Schedule</div>
            <div class="scheduleBox">
                <img src="../static/image/sleepy.png">
                <div class="scheduleText">
                    <p>오늘의 일정이 없습니다.</p>
                </div>
            </div>
        </div>
        <div class="right"></div>
    </div>
</body>
</html>

templates/profile.html
{% extends 'base.html' %} 
{% load static %} 

{% block content %}
<div class="EditTitle">
    <a href="{% url 'profile' id=user.id %}">
        <p>Your Profile</p>
    </a>
</div>

<div class="profile">
    <i class="fa-solid fa-gear fa-2xl"></i>
    <p>프로필 편집</p>
    <div class="btnContainer">
        <a href="{% url 'accounts:logout' %}">
            <button id="logout">
                    로그아웃<i class="fa-solid fa-arrow-right-from-bracket"></i>
            </button>
        </a>
        <form action="{% url 'accounts:delete' %}" method="POST">
            {% csrf_token %}
            <input type="submit" id="deleteBtn" value="회원 탈퇴">
        </form>
    </div>
</div>

<div>
    <div class="profilebox">
        <p id="uname">{{ user.nickname }}</p>
        <div class="emailbox">{{ user.email }}</div>
        <div class="photoEdit">
            <img class="photo"style="width:15vw; height:15vw" {% if user.image %}src="{{user.image.url}}"{% endif %} alt="이미지"></img>
            <button id="rephoto">
                <i class="fa-solid fa-pen fa-xl"></i>
            </button>
        </div>
        <div class="EmailContainer">
            <p id="Email">E-mail</p>
            <p id="Emailtext">{{ user.email }}</p>
        </div>
        <div class="ExplainContainer1">
            <p id="Explain">소개글</p>
        </div>
        <div class="ExplainContainer2">
            <p id="explaintext">{{ user.introduction }}</p>
        </div>
        <div class="buttonContainer">
            <button id="edit" onclick="redirectToProfile({{ user.id }})">수정하기 <span style=font-weight:600;></span></button>
        </div>
    </div>
<div>
<script src="{% static 'javascript/profile.js' %}"></script>
<script>
    function redirectToProfile(id) {
        console.log(id, "아아아ㅏ");
        window.location.href = "/profile/edit/" + id + "/";
    }    
</script>
{% endblock %}

templates/profile_form.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="EditTitle">
    <a href="{% url 'profile' id=user.id %}">
        <p>Edit Profile</p>
    </a>
</div>
<div class="profile">
    <i class="fa-solid fa-gear fa-2xl"></i>
    <p>프로필 편집</p>
</div>

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="profilebox">
        <input type="text" id="name" name="nickname" value="{{ user.nickname }}" />
        <div class="emailbox">{{ user.email }}</div>
        <div class="photoEdit">
        <img class="photo" id="previewImage1" {% if user.image %}src="{{user.image.url}}"{% endif %} alt=""></img>
        <div id="rephoto">
            <label for="imageFile1">
            <i class="fa-solid fa-pen fa-xl"></i>
            </label>
            <input type="file" name="image" accept="image/*" id="imageFile1" style="display: none;">
        </div>
        <input type="file" name="image" accept="image/*" id="imageFile1" style="display: none"/>
        </div>
        <div class="EmailContainer">
        <p id="Email">E-mail</p>
        <p id="EmailText">{{ user.email }}</p>
        </div>
        <div class="ExplainContainer1">
        <p id="Explain">소개글</p>
        </div>
        <div class="ExplainContainer2">
        <input type="text" id="explaintext" name="introduction" value="{{ user.introduction }}" />
        </div>
        <div class="buttonContainer">
        <input type="submit" value="저장하기" id="edit">
            <span style="font-weight: 600"></span>
        </input>
        </div>
    </div>
</form>
<script src="{% static 'javascript/profile.js' %}"></script>
<script>
    // 이미지 선택하면 보여주기 
    var imageFileInput = document.getElementById('imageFile1');
    var previewImage = document.getElementById('previewImage1');

    imageFileInput.addEventListener('change', function() {
    var file = imageFileInput.files[0];
    var reader = new FileReader();

    reader.onload = function(e) {
        previewImage.src = e.target.result;
        previewImage.style.width = '15vw'; // 이미지의 크기를 50%로 조절
        previewImage.style.height = '15vw'; // 이미지의 높이를 자동으로 조정
    };

    reader.readAsDataURL(file);
    });

</script>
{% endblock %}

templates/warning.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LisaMate</title>
    <link rel="stylesheet" href="../static/css/warning.css">
    <script src="https://kit.fontawesome.com/d4b61b3d04.js" crossorigin="anonymous"></script>
</head>
<body>
    
        <div class="warning" style="margin-left:30%;">
                <i class="fa-regular fa-square-check fa-2xl" style="color: #ffffff;"></i>
                <hr class="warning_hr">
                <i class="fa-solid fa-triangle-exclamation"></i>
                <p class="warning_text">이 페이지를 찾을 수 없습니다.</p>
                <hr class="warning_hr">
        </div>


    </div>


</body>
</html>