accounts/urls.py
from django.urls import path
from .views import signup_view, login_view, logout_view, delete_view

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('delete/', delete_view, name='delete'),
]

checklist/urls.py
from django.urls import path

from .views import index, create_schedule_view, calendar_view, get_schedule_view, update_schedule_view, delete_schedule_view

app_name = 'checklist'

urlpatterns = [
    path('', index, name='index'),
    path('calendar/', calendar_view, name='calendar'),
    path('create_schedule/', create_schedule_view, name='schedule-create'),
    path('calendar/get_schedule/', get_schedule_view, name='schedule-get'),
    path('edit/<int:id>/', update_schedule_view, name='schedule-update'),
    path('delete/<int:id>/', delete_schedule_view, name='schedule-delete'),

]

informationPost/urls.py
from django.urls import path

from .views import index, post_create_form_view, board_list_view, board_topic_list_view, post_detail_view, post_update_view, post_delete_view, create_comment_view, delete_comment_view

app_name = 'boards'

urlpatterns=[
    path('', index),
    path('new/', post_create_form_view, name='post-create'),  # 게시물 작성 페이지
    path('<int:id>/delete/', post_delete_view, name='post-delete'),
    path('<str:board_type>/<str:topic>/<int:id>/edit/', post_update_view, name='post-update'),
    path('create_comment/<int:post_id>/', create_comment_view, name='create-comment'),
    path('delete_comment/<int:comment_id>/', delete_comment_view, name='delete-comment'),
    path('<str:board_type>/<str:topic>/<int:id>/', post_detail_view, name='board-topic-detail'),
    path('<str:board_type>/<str:topic>/', board_topic_list_view, name='board-topic-list'),
    path('<str:board_type>/', board_list_view, name='board-list'),
]

lisamate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from lisamate.views import ProfileView, update_profile_view, index2
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='checklist:index', permanent=False)),
    path('checklist/', include('checklist.urls', namespace='checklist')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('profile/', index2),
    path('profile/<int:id>', ProfileView.as_view(), name='profile'),
    path('boards/', include('informationPost.urls', namespace='informationPost')),
    path('profile/edit/<int:id>/', update_profile_view, name='edit-user'),
]

# MEDIA_URL로 들어오면 MEDIA_ROOT에서 정의한 걸 찾아서 사용
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'lisamate.views.warning_view'

checklist/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Schedule(models.Model):
    content = models.TextField(verbose_name='작성 내용')
    date = models.DateField(verbose_name='날짜', null=True) # date(2023,6,15)
    duration = models.CharField(
        verbose_name='기간',
        choices=(
            ('before', '이사 전'),
            ('doing', '이사 중'),
            ('done', '이사 후'),
        ),
        max_length=10
    )
    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name='schedules', null=True, blank=True)
    is_checked = models.BooleanField(verbose_name='체크 여부', default=False)

    def __str__(self):
        return self.content

checklist/views.py
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect
from .models import Schedule
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from datetime import date, datetime
from django.db.models import Q

def index(request):
    if not request.user.is_authenticated:
        return redirect('accounts:login')  # 로그인 페이지로 리디렉션

    # 작성자가 None이거나 현재 로그인한 사용자인 Schedule 객체 필터링
    schedules = Schedule.objects.filter(Q(writer=None) | Q(writer=request.user))

    user = request.user  # 로그인한 사용자 정보 가져오기
    now = datetime.combine(date.today(), datetime.min.time()).date()

    context = {
        'schedules': schedules,
        'now': now,
        'user': user,
    }

    return render(request, 'checklist/checklist.html', context)

def calendar_view(request):
    user = request.user  # 로그인한 사용자 정보 가져오기
    schedules = Schedule.objects.filter(writer=user)  # 해당 사용자의 Schedule 객체 필터링
    # schedules = Schedule.objects.all()
    now = datetime.combine(date.today(), datetime.min.time()).date()
    context = {
        'schedules': schedules,
        'now': now,
    }
    
    return render(request, 'checklist/cal.html', context)

@csrf_exempt
def create_schedule_view(request):
    if request.method == 'POST':
        content = request.POST.get('content')
        year = request.POST.get('year')
        month = request.POST.get('month')
        day = request.POST.get('day')
        duration = request.POST.get('duration')
        writer=request.user
        
        print(duration)
        # Schedule 모델에 새로운 객체 생성 및 저장
        schedule = Schedule(
            content=content,
            date=f"{year}-{month}-{day}",
            duration=duration,
            writer=writer
        )
        schedule.save()

        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False, 'message': 'Invalid request method'})
    

@login_required
def get_schedule_view(request):
    year = request.GET.get('year')
    month = request.GET.get('month')
    user_email = request.user.email

    schedules = Schedule.objects.filter(writer__email=user_email, date__year=year, date__month=month)
    schedule_data = [{'content': schedule.content, 'date': schedule.date} for schedule in schedules]

    return JsonResponse({'schedules': schedule_data})


def update_schedule_view(request, id=None):
    schedule = get_object_or_404(Schedule, id=id)  # 해당 ID에 해당하는 Schedule 객체 가져오기

    if request.method == 'POST':
        content = request.POST.get('content')
        year = request.POST.get('year')
        month = request.POST.get('month')
        day = request.POST.get('day')
        duration = request.POST.get('duration')
        
        print(duration)
        # Schedule 객체 수정 및 저장
        schedule.content = content
        schedule.date = f"{year}-{month}-{day}"
        schedule.duration = duration
        schedule.save()

        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False, 'message': 'Invalid request method'})
    

def delete_schedule_view(request, id):
    if request.method == 'GET':
        schedule = get_object_or_404(Schedule, id=id)
        schedule.delete()
        
        return redirect('checklist:index')

templates/checklist/cal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LisaMate</title>
    <link rel="stylesheet" href="{% static 'css/cal.css' %}">
</head>

<body>
    <div class="Middle">
        <div class="Mcircle"></div>
    </div>
    <div class="top">
        <p>My Check list</p>
        <div class="icon">
            <a href="{% url 'profile' id=user.id%}" ><i class="fa-solid fa-user fa-2xl"></i></a>
            <a href="{% url 'checklist:index' %}" ><i class="fa-solid fa-house fa-2xl"></i></a>
        </div>
    </div>

    <div class="logo">
        <a href="{% url 'checklist:index' %}">
            <p>LISA MATE</p>
        </a>
    </div>

    <div class="middleTitle">
        <a href="{% url 'checklist:index' %}">
            <p id="CL">Checklist</p>
        </a>
        <p id="bar">|</p>
        <a href="{% url 'checklist:calendar' %}">
            <p id="Cal">Calendar</p>
        </a>
    </div>

    <div class="all">
        <div class="left">
            <div class="userBox">
                <div class="user">USER</div>
                <div class="userbox">
                    <img class="userImage" {% if user.image %}src="{{user.image.url}}"{% endif %}></img>
                    <div class="name">{{ user.nickname }}</div>
                    <div class="email">{{ user.email}}</div>
                    <div class="explain">{{ user.introduction }}</div>
                    <div class="button-container">
                        <a href="{% url 'boards:post-create' %}">
                            <button type="button" id="pen">
                                <img src="{% static 'image/pen.png' %}">글쓰기
                            </button>
                        </a>
                        <a href="{% url 'profile' id=user.id %}">
                            <button type="button" id="setting">
                                <img src="{% static 'image/setting.png' %}">프로필 편집/설정
                            </button>
                        </a>
                    </div>
                </div>
            </div>

            <div class="menu">
                <div class="checklist">체크리스트</div>
                <div class="checklistcircle"></div>
                <div class="text1">
                    <div class="checklistText">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'checklist:index' %}">
                            <p>체크리스트</p>
                        </a>
                    </div>
                    <div class="calText">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'checklist:calendar' %}">
                            <p>캘린더</p>
                        </a>
                    </div>
                </div>
                <div class="noticeboard">게시판</div>
                <div class="noticeboardcircle"></div>
                <div class="text2">
                    <div class="notice">
                        <a href="{% url 'informationPost:board-list' board_type='information' %}">
                            <p>정보 게시판</p>
                        </a>
                    </div>
                    <div class="monthly">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='information' topic='월세' %}">
                            <p>월세 정보 공유</p>
                        </a>
                    </div>
                    <div class="Jeonse">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='information' topic='전세' %}">
                            <p>전세 정보 공유</p>
                        </a>
                    </div>
                    <div class="bargain">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='information' topic='매매' %}">
                            <p>매매 정보 공유</p>
                        </a>
                    </div>
                    <hr>
                </div>
                <div class="text3">
                    <div class="review">
                        <a href="{% url 'informationPost:board-list' board_type='review' %}">
                            <p>후기 게시판</p>
                        </a>
                    </div>
                    <div class="monthlyReview">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='review' topic='월세' %}">
                            <p>월세 후기</p>
                        </a>
                    </div>
                    <div class="JeonseReview">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='review' topic='전세' %}">
                            <p>전세 후기</p>
                        </a>
                    </div>
                    <div class="bargainReview">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='review' topic='매매' %}">
                            <p>매매 후기</p>
                        </a>
                    </div>
                    <hr>
                </div>
                <div class="text4">
                    <div class="town">
                        <a href="{% url 'informationPost:board-list' board_type='hometown' %}">
                            <p>우리동네 게시판</p>
                        </a>
                    </div>
                    <div class="situation">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='hometown' topic='우리동네' %}">
                            <p>우리동네 현황</p>
                        </a>
                    </div>
                    <div class="criminal">
                        <i class="fa-solid fa-circle fa-xs"></i>
                        <a href="{% url 'informationPost:board-topic-list' board_type='hometown' topic='범죄자' %}">
                            <p>범죄자 거주 정보</p>
                        </a>
                    </div>
                </div>
            </div>
        
            <div class="scheduleTitle">Schedule</div>
            {% block schedule_data %}
            {% if schedules %}
                <br>
                <div class="scheduleBox">
                    {% for schedule in schedules %}
                        {% if schedule.date and schedule.date|date:"Y-m-d" == now|date:"Y-m-d" %}
                            <div class="scheduleText">
                                <p>{{ schedule.date|date:"m/d" }}</p>
                                <p>{{ schedule.content }}</p>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            {% else %}
                <div class="scheduleBox">
                    <img src="{% static 'image/sleepy.png' %}">
                    <div class="scheduleText"> 
                        <p>오늘의 일정이 없습니다.</p>
                    </div>
                </div>
            {% endif %}
            {% endblock %} 
    
        </div>
        <div class="right">
            <div class="calendarbox">
                <div class="Calendar1">
                    <div class="Container">
                        <i class="fa-regular fa-calendar fa-2xl"></i>
                        <div class="ctext">
                            <p>Calendar</p>
                        </div>
                    </div>
                    <div class="innerCalendar">
                        <div class="calendar">
                            <div class="header">
                                <div class="year-month"></div>
                                <div class="nav">
                                    <button class="nav-btn go-prev" onclick="prevMonth()">&lt;</button>
                                    <button class="nav-btn go-today"></button>
                                    <button class="nav-btn go-next" onclick="nextMonth()">&gt;</button>
                                </div>
                            <div class="year-month2"></div>
                        </div>
                        <div class="main" onclick="openModal()">
                            <div class="days">
                                <div class="day">일</div>
                                <div class="day">월</div>
                                <div class="day">화</div>
                                <div class="day">수</div>
                                <div class="day">목</div>
                                <div class="day">금</div>
                                <div class="day">토</div>
                            </div>
                        <div class="dates">
                        </div>
                    </div>
                </div>
            </div>
            <div id="modal" class="modal">
                <div class="modal-content" id="modal-content">
                    <div class="modalTop">
                        <p id="modal-close" onclick="closeModal()">LISA MATE</p>
                        <div class="rightContainer">
                            <div class="text4">
                                <p>Checklist</p>
                            </div>
                            <p>|</p>
                            <div class="text6">
                                <p>Calendar</p>
                            </div>
                        </div>
                    </div>

                    <div class="modalBox">
                        <div class="modalbox"></div>
                        <div class="modalbar"></div>
                        <div class="modalcircle"></div>
                        <div class="modalinner"></div>
                        <i class="fa-regular fa-calendar fa-2xl"></i>
                        <div class="ctext2">Calendar</div>
                        <div class="inner"></div>
                    </div>
                    <div class="modalcalendar">
                        <div class="modalheader">
                            <div class="modal-year-month"></div>
                            <div class="modalnav">
                                <button class="modalnav-btn modal-go-prev" onclick="prevMonth2()">&lt;</button>
                                <button class="modalnav-btn modal-go-today"></button>
                                <button class="modalnav-btn modal-go-next" onclick="nextMonth2()">&gt;</button>
                            </div>
                            <div class="modal-year-month2"></div>
                        </div>
                        <div class="modalmain">
                            <div class="modaldays">
                                <div class="modalday">일</div>
                                <div class="modalday">월</div>
                                <div class="modalday">화</div>
                                <div class="modalday">수</div>
                                <div class="modalday">목</div>
                                <div class="modalday">금</div>
                                <div class="modalday">토</div>
                            </div>
                            <div class="modaldates"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="leftbar"></div>
        <div class="leftcircle"></div>
    </div>
</body>
    <script src="../../static/javascript/cal.js"></script>
    <script src="https://kit.fontawesome.com/d4b61b3d04.js" crossorigin="anonymous"></script>
</html>

templates/checklist/checklist.html
{% extends 'base.html' %}
{% load static %}
{% block schedule_data %}
{% if schedules %}
<style>
    .all>.left>.menu>.text1>.checklistText {
        background: radial-gradient(50% 50% at 50% 50%, #87B3FF 0%, rgba(135, 179, 255, 0) 100%);
    }

    .all>.left>.menu>.text1>.checklistText>i,
    .all>.left>.menu>.text1>.checklistText>a>p {
        color: #0418AB;
        font-weight: 600;
    }
</style>

<div class="scheduleBox">
    {% for schedule in schedules %}
    {% if schedule.date and schedule.date|date:"Y-m-d" == now|date:"Y-m-d" %}
    <div class="scheduleText">
        <p>{{ schedule.date|date:"m/d" }}</p>
        <p>{{ schedule.content }}</p>
    </div>
    {% endif %}
    {% endfor %}
</div>
{% else %}
<div class="scheduleBox">
    <img src="{% static 'image/sleepy.png' %}">
    <div class="scheduleText">
        <p>오늘의 일정이 없습니다.</p>
    </div>
</div>
{% endif %}
{% endblock %}

{% block content %}
<script src="../../static/javascript/checklist.js"></script>

<div class="middleTitle1">
    <a href="{% url 'checklist:index' %}">
        <p id="CL1">Checklist</p>
    </a>
    <p id="bar1">|</p>
    <a href="{% url 'checklist:calendar' %}">
        <p id="Cal1">Calendar</p>
    </a>
</div>

<div class="exambox" style="margin-left:10%;">
    <i class="fa-regular fa-square-check fa-2xl" style="color: #ffffff;"></i>
    <p class="box_title">부기의<br>이사 체크리스트</p>
    <hr class="box_hr">
    <p class="box_text1">Lisa가 추천하는 기본 체크리스트 항목</p>
    <p class="box_text2">부기가 추천하는 기본 체크리스트 항목</p>
    <a href="{% url 'checklist:index' %}">
        <p class="box_text3">나의 추가 체크리스트 항목</p>
    </a>
    <p class="box_text4">+</p>
</div>

<div class="checkbox" style="margin-left:10%;">
    <p class="check_text1">이사 전</p>
    {% for schedule in schedules %}
    {% if schedule.duration == 'before' %}
    <div class="first_checkbox">
        {% if schedule.is_checked %}
        <i class="fa-regular fa-check-square"></i>
        {% else %}
        <i class="fa-regular fa-square"></i>
        {% endif %}
        <p class="first_checkbox_text">{{schedule.content}}</p>
        <button class="editBtn1"
            onclick="editModal('{{ schedule.content }}', '{{ schedule.date.year }}', '{{ schedule.date.month }}', '{{ schedule.date.day }}', '{{ schedule.duration }}', '{{ schedule.id }}')"><i
                class="fa-solid fa-pen"></i></button>
        <button class="removeBtn1" onclick="confirmDelete('{{ schedule.id }}')"><i class="fa-solid fa-x"></i></button>
    </div>
    {%endif%}
    {% endfor %}
    <p class="check_text2">이사 중</p>
    {% for schedule in schedules %}
    {% if schedule.duration == 'doing' %}
    <div class="second_checkbox">
        {% if schedule.is_checked %}
        <i class="fa-regular fa-check-square"></i>
        {% else %}
        <i class="fa-regular fa-square"></i>
        {% endif %}
        <p class="second_checkbox_text">{{schedule.content}}</p>
        <button class="editBtn2"
            onclick="editModal('{{ schedule.content }}', '{{ schedule.date.year }}', '{{ schedule.date.month }}', '{{ schedule.date.day }}', '{{ schedule.duration }}', '{{ schedule.id }}')"><i
                class="fa-solid fa-pen"></i></button>
        <button class="removeBtn2" onclick="confirmDelete('{{ schedule.id }}')"><i class="fa-solid fa-x"></i></button>
    </div>
    {%endif%}
    {% endfor %}
    <p class="check_text3">이사 후</p>
    {% for schedule in schedules %}
    {% if schedule.duration == 'done' %}
    <div class="third_checkbox">
        {% if schedule.is_checked %}
        <i class="fa-regular fa-check-square"></i>
        {% else %}
        <i class="fa-regular fa-square"></i>
        {% endif %}
        <p class="third_checkbox_text">{{schedule.content}}</p>
        <button class="editBtn3"
            onclick="editModal('{{ schedule.content }}', '{{ schedule.date.year }}', '{{ schedule.date.month }}', '{{ schedule.date.day }}', '{{ schedule.duration }}', '{{ schedule.id }}')"><i
                class="fa-solid fa-pen"></i></button>
        <button class="removeBtn3" onclick="confirmDelete('{{ schedule.id }}')"><i class="fa-solid fa-x"></i></button>
    </div>
    {%endif%}
    {% endfor %}
    <i class="fa-solid fa-plus"></i>
    <div class="plusbox" onclick="openModal()">
        <button id="plusBtn" type="submit">
            <i class="fa-solid fa-circle-plus"> 직접 추가하기</i>
        </button>
    </div>
</div>
</div>

<div class="modal-container" id="modalContainer">
    <div class="modal" id="modal">
        <p id="ModalTitle">
            <i class="fa-solid fa-circle-plus"> 직접 추가하기</i>
            <i class="fa-solid fa-repeat fa-lg" id="close" onclick="closeModal()"></i>
        </p>
        <p id="modal_firsttext">작성 내용</p>
        <input type="text" id="modal_Input" placeholder="일정을 입력해주세요">
        <p id="modal_secondtext">날짜 선택</p>
        <div class="dropbox">
            <select id="year" onchange="updateDayOptions()">
                <option value="2023">2023년</option>
                <option value="2024">2024년</option>
                <option value="2025">2025년</option>
                <option value="2026">2026년</option>
                <option value="2027">2027년</option>
                <option value="2028">2028년</option>
                <option value="2029">2029년</option>
            </select>

            <select id="month" onchange="updateDayOptions()">
                <option value="01">1월</option>
                <option value="02">2월</option>
                <option value="03">3월</option>
                <option value="04">4월</option>
                <option value="05">5월</option>
                <option value="06">6월</option>
                <option value="07">7월</option>
                <option value="08">8월</option>
                <option value="09">9월</option>
                <option value="10">10월</option>
                <option value="11">11월</option>
                <option value="12">12월</option>
            </select>

            <select id="day">
                <option value="01">1일</option>
                <option value="02">2일</option>
                <option value="03">3일</option>
                <option value="04">4일</option>
                <option value="05">5일</option>
                <option value="06">6일</option>
                <option value="07">7일</option>
                <option value="08">8일</option>
                <option value="09">9일</option>
                <option value="10">10일</option>
                <option value="11">11일</option>
                <option value="12">12일</option>
                <option value="13">13일</option>
                <option value="14">14일</option>
                <option value="15">15일</option>
                <option value="16">16일</option>
                <option value="17">17일</option>
                <option value="18">18일</option>
                <option value="19">19일</option>
                <option value="20">20일</option>
                <option value="21">21일</option>
                <option value="22">22일</option>
                <option value="23">23일</option>
                <option value="24">24일</option>
                <option value="25">25일</option>
                <option value="26">26일</option>
                <option value="27">27일</option>
                <option value="28">28일</option>
                <option value="29">29일</option>
                <option value="30">30일</option>
                <option value="31">31일</option>
            </select>
        </div>

        <p id="modal_thirdtext">기간 지정</p>
        <div class="checkboxContainer">
            <div class="checkbox_period" id="item1" value="before" onclick="toggleCheckbox('item1')">이사전</div>
            <div class="checkbox_period" id="item2" value="doing" onclick="toggleCheckbox('item2')">이사중</div>
            <div class="checkbox_period" id="item3" value="done" onclick="toggleCheckbox('item3')">이사후</div>
        </div>
        <button id="create" onclick="createData('{{id}}')">완료</button>
    </div>
</div>
<script>
    function editModal(content, year, month, day, duration, id) {
        const modalContainer = document.getElementById('modalContainer');
        modalContainer.style.display = 'flex';

        // 모달 내부에 값을 표시하는 작업 수행
        document.getElementById('modal_Input').value = content;
        document.getElementById('year').value = year;
        document.getElementById('month').value = addLeadingZero(month);
        document.getElementById('day').value = addLeadingZero(day);

        console.log(duration)

        // 기간 선택 체크박스 처리
        var checkboxPeriods = document.getElementsByClassName('checkbox_period');
        for (var i = 0; i < checkboxPeriods.length; i++) {
            checkboxPeriods[i].classList.remove('active');
            if (checkboxPeriods[i].getAttribute('value') === duration) {
                checkboxPeriods[i].classList.add('active');
                checkboxPeriods[i].style.background = '#5377FF'; // 배경색 변경
            }
        }

        //id 값 넘겨줌
        document.getElementById('create').onclick = function () {
            createData(id);
        };
    }

    // 1의 자리 숫자에 앞에 0을 붙여주는 함수
    function addLeadingZero(number) {
        return number < 10 ? '0' + number : number;
    }

    function confirmDelete(scheduleId) {
        var result = confirm("정말로 삭제하시겠습니까?");
        if (result) {
            var url = "{% url 'checklist:schedule-delete' id=0 %}".replace('0', scheduleId);
            window.location.href = url;
        } else {
            // 삭제 취소
        }
    }
</script>
{% endblock %}